{
 "title": "Go Log Anomaly Detector",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Logs (5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(lad_logs_ingested_total[5m]))"
    }
   ]
  },
  {
   "title": "Anomalias (5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(lad_anomalies_total[5m]))"
    }
   ]
  },
  {
   "title": "Eventos por regra (janela)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "lad_window_count", "legendFormat": "{{rule}}" }
   ]
  }
 ]
}