apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-orchestrator
  namespace: sre-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy-orchestrator
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","watch","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy-orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deploy-orchestrator
subjects:
  - kind: ServiceAccount
    name: deploy-orchestrator
    namespace: sre-tools