name: CI
on:
  push: { branches: [ main, master ] }
  pull_request: { branches: [ main, master ] }

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: "1.22.x", cache: true }
      - run: go mod tidy
      - run: go build ./...
      - run: go test ./... -v