name: Deploy Canary

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag da imagem (ex: 1.2.3)"
        required: true

jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
      - name: Disparar deploy canary
        run: |
          curl -XPOST "$ORCHESTRATOR_URL/deploys" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $ORCHESTRATOR_TOKEN" \
            -d '{
              "app": "myapp",
              "namespace": "default",
              "image": "repo/myapp:${{ github.event.inputs.image_tag }}",
              "strategy": "canary",
              "params": { "canaryStep": "20", "canaryPause": "45", "maxError": "0.02", "maxP95": "0.5" },
              "requireApproval": false
            }'