{
 "title": "Go Alert Router",
 "tags": [
  "alerts",
  "router",
  "devops"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Alertas ingeridos (5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(alert_router_ingested_total[5m]))"
    }
   ]
  },
  {
   "title": "Descartes (5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(alert_router_dropped_total[5m]))"
    }
   ]
  },
  {
   "title": "Entregas (5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(alert_router_deliveries_total[5m]))"
    }
   ]
  },
  {
   "title": "Erros de entrega (5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(alert_router_delivery_errors_total[5m]))"
    }
   ]
  },
  {
   "title": "Ingestão por fonte (alerts/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (source) (rate(alert_router_ingested_total[2m]))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Entregas por destino (entregas/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (dest) (rate(alert_router_deliveries_total[2m]))",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  {
   "title": "Drop por razão (drops/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (reason) (rate(alert_router_dropped_total[2m]))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Fila por rota (depth)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "expr": "alert_router_queue_depth", "legendFormat": "{{route}}" }
   ]
  }
 ]
}