apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
  labels:
    app: myapp
    track: green
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
      track: green
  template:
    metadata:
      labels:
        app: myapp
        track: green
    spec:
      containers:
        - name: myapp
          image: repo/myapp:1.0.0
          ports:
            - containerPort: 8080