apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-restarter
  namespace: sre-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-restarter
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-restarter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-restarter
subjects:
  - kind: ServiceAccount
    name: pod-restarter
    namespace: sre-tools