{
 "title": "Go Access Auditor",
 "tags": [
  "security",
  "audit",
  "devops"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Eventos (5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(access_auditor_events_ingested_total[5m]))"
    }
   ]
  },
  {
   "title": "Sensíveis (5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(access_auditor_sensitive_matches_total[5m]))"
    }
   ]
  },
  {
   "title": "Eventos por source (rps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (source) (rate(access_auditor_events_ingested_total[2m]))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Sensíveis por regra (rps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (rule) (rate(access_auditor_sensitive_matches_total[2m]))",
     "legendFormat": "{{rule}}"
    }
   ]
  }
 ]
}