version: "3.8"
services:
  monitor:
    build: .
    image: go-sre-monitor:local
    container_name: monitor
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/app/configs/services.yaml
      - HTTP_ADDR=:8080
      - LOG_LEVEL=info
      - PROBE_INTERVAL=15s

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on: [monitor]

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./configs/grafana-provisioning:/etc/grafana/provisioning
    depends_on: [prometheus]