apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-exporter
  namespace: monitoring-lab
  labels:
    app: healthcheck-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcheck-exporter
  template:
    metadata:
      labels:
        app: healthcheck-exporter
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: exporter
          image: healthcheck-exporter:latest
          imagePullPolicy: IfNotPresent
          args:
            - -urls=https://example.com,https://httpbin.org/status/500
            - -interval=30s
            - -timeout=3s
            - -concurrency=5
            - -port=:8080
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: healthcheck-exporter
  namespace: monitoring-lab
  labels:
    app: healthcheck-exporter
spec:
  type: ClusterIP
  selector:
    app: healthcheck-exporter
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: healthcheck-exporter
  namespace: monitoring-lab
  labels:
    release: lab-prom
spec:
  selector:
    matchLabels:
      app: healthcheck-exporter
  namespaceSelector:
    matchNames:
      - monitoring-lab
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 5s
      scheme: http